apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: amf-example
  namespace: amf-example
spec:
  provider: amf.openairinterface.org
  capacity:
    maxSubscribers: 200
  interfaces:
  - name: n2
    ipv4:
      address: 192.168.8.43/24
      gateway: 192.168.8.1
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  parametersRefs:
  - name: oai-amf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig