apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n2
  annotations:
    nephio.org/network-name: n2
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.amf-example
    specializer.nephio.org/namespace: example
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  networkInstance:
    name: default
  cniType: macvlan
  attachmentType: vlan