apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: amf-example-n2
  namespace: amf-example
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "ens6",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.8.43/24",
            "gateway": "192.168.8.1"
          }
        ]
      }
    }'
