apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: smf-example-n4
  namespace: smf-example
spec:
  config: '{"cniVersion":"0.3.1","name": "smf-core-n4","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens5","mode":"bridge","ipam":{"type":"static"}}]}'