apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: smf-example-n4
  namespace: smf-example
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "capabilities": {
          "ips": true
        },
      "master": "ens7",
      "mode": "l3",
      "ipam": {
        "type": "static"
      }
    }'
