apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: smf-example
  namespace: smf-example
spec:
  provider: smf.openairinterface.org
  capacity:
    maxNFConnections: 10
    maxSessions: 500
  interfaces:
  - name: n4
    ipv4:
      address: 192.168.9.55/24 #SMF_N4_IP
      gateway: 192.168.9.1 #SMF_N4_GW
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  parametersRefs:
  - name: oai-smf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
