apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace
  annotations:
    config.kubernetes.io/local-config: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  namespace: oai-core