apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n3
  annotations:
    nephio.org/network-name: n3
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.upf-example
    specializer.nephio.org/namespace: example
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  networkInstance:
    name: vpc-ran
  cniType: ipvlan
  attachmentType: vlan
