apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-example-n3
  namespace: upf-example
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "capabilities": {
          "ips": true
        },
      "master": "ens5",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": " 192.168.1.149/24",
            "gateway": " 192.168.1.1"
          }
        ]
      }
    }'
