apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n4
  namespace: oai-core
spec:
  config: '{"cniVersion":"0.3.1","name": "upf-edge-n4","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth0","mode":"bridge","ipam":{"type":"static"}}]}' 