apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-example-n4
  namespace: upf-example
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "ens5",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.10.135.10/20",
            "gateway": "10.10.128.1"
          }
        ]
      }
    }'
