apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-example-n6
  namespace: upf-example
spec:
  config: config: '{ "cniVersion": "0.3.1", "type": "ipvlan", "capabilities": { "ips": true }, "master": "ens7", "mode": "l3", "ipam": { "type": "static" } }'
