apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n6
  namespace: oai-core
spec:
  config: '{"cniVersion":"0.3.1","name": "upf-edge-n6","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens6","mode":"bridge","ipam":{"type":"static"}}]}'