################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the terms found in the LICENSE file in the root of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
##################################################################################
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n3
  namespace: example
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n6
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities":
    { "ips": true }, "master": "ens5", "mode": "l2", "ipam": { "type": "static", "routes":
    [ { "dst": "0.0.0.0/0", "gw": "10.100.50.238" } ] } } ] }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n4
  namespace: example
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n6
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities":
    { "ips": true }, "master": "ens5", "mode": "l2", "ipam": { "type": "static", "routes":
    [ { "dst": "0.0.0.0/0", "gw": "10.100.50.246" } ] } } ] }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n6
  namespace: example
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n6
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities":
    { "ips": true }, "master": "ens5", "mode": "l2", "ipam": { "type": "static", "routes":
    [ { "dst": "0.0.0.0/0", "gw": "10.10.128.1" } ] } } ] }'
