apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-eni-ip-config
data:
  assign-ips.sh: |
    #!/bin/bash
    yum install -y aws-cli
    echo "Fetching instance ID..."
    INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
    echo "Instance ID: $INSTANCE_ID"
    REGION="ap-northeast-2"
    #SECONDARY_IPS=("10.10.135.10" "10.10.135.11" "10.10.135.12")
    SECONDARY_IPS=("10.10.135.10")
    echo "Fetching ENI ID..."
    ENI_ID=$(aws ec2 describe-instances --instance-id $INSTANCE_ID --region $REGION --query "Reservations[].Instances[].NetworkInterfaces[0].NetworkInterfaceId" --output text)
    echo "ENI ID: $ENI_ID"
    for IP in "${SECONDARY_IPS[@]}"; do
      echo "Assigning IP address: $IP..."
      aws ec2 assign-private-ip-addresses --network-interface-id $ENI_ID --private-ip-addresses $IP --allow-reassignment --region $REGION
    done
    echo "Script execution completed."